DOC: Fix docs in styling exercise.
"normal" is no longer a valid option. It raises the following:

ValueError: expected an element of either Enum('horizontal',
            'vertical') or Float, got 'normal'