try/except block to improve PyPy compatibility
Since PyPy doesn't support datetime64  "AttributeError: 'module' object has no attribute 'datetime64' " is raised. Skipping this exception will allow basic plotting features using PyPy.

Check here for some more details:
http://stackoverflow.com/questions/37570376/is-there-any-2d-plotting-library-compatible-with-pypy/37588552#37588552